sudo: false
dist: trusty
language: python
python:
  - 2.7
cache: pip
install:
  - pip install --upgrade pip
  - pip install codecov
  - pip install -r requirements.txt
  - pip install -e .
script:
  - nosetests tests/ -v --with-coverage
after_success:
  - codecov
